#!/usr/bin/env bash
# derive-ipv4-netplan.sh — emit an IPv4-only netplan for the host's primary
# interface, DERIVED from the live system rather than hardcoded, so it stays
# correct on a rebuilt or re-addressed instance.
#
# WHY THIS EXISTS: the node's IPv6 egress to ghcr.io is dead (connection reset),
# but containerd resolves AAAA and tries IPv6 FIRST, so image pulls fail and
# never self-heal. sysctl.d alone could not hold it — `all`/`default` only apply
# to interfaces created AFTER systemd-sysctl runs, and eth0 comes up later via
# systemd-networkd carrying the static IPv6 address cloud-init wrote for it.
# Declaring the interface IPv4-only removes the address instead of racing it.
#
# Writes YAML to stdout. Exits 2 if the IPv4 config cannot be derived — the
# caller must then leave the existing netplan alone rather than emit a partial
# file that could strand the host.
#
# Overridable for testing: NETPLAN_RESOLV_CONF, and the ip/resolvectl binaries
# are resolved from PATH.
set -euo pipefail

resolv_conf="${NETPLAN_RESOLV_CONF:-/run/systemd/resolve/resolv.conf}"

iface="$(ip -4 route show default 2>/dev/null | awk '{print $5; exit}')"
cidr=""
gw="$(ip -4 route show default 2>/dev/null | awk '{print $3; exit}')"
[[ -n "$iface" ]] && cidr="$(ip -4 -o addr show dev "$iface" 2>/dev/null | awk '{print $4; exit}')"

# Upstream resolvers, NOT /etc/resolv.conf: on a systemd-resolved host that file
# holds only the 127.0.0.53 stub, and writing the stub into netplan points
# resolution at itself. IPv6 resolvers are dropped deliberately — with no IPv6
# route they would only ever time out.
# `|| true` matters: under `set -euo pipefail` a missing resolv_conf (or a grep
# that matches nothing) would abort here and the resolvectl fallback below would
# be unreachable dead code.
dns="$(awk '/^nameserver/ {print $2}' "$resolv_conf" 2>/dev/null \
  | grep -v ':' | grep -v '^127\.' | paste -sd, - || true)"
if [[ -z "$dns" ]]; then
  dns="$(resolvectl dns 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | grep -v '^127\.' | sort -u | paste -sd, - || true)"
fi

if [[ -z "$iface" || -z "$cidr" || -z "$gw" || -z "$dns" ]]; then
  echo "derive-ipv4-netplan: could not derive IPv4 config (iface=${iface:-?} cidr=${cidr:-?} gw=${gw:-?} dns=${dns:-?})" >&2
  exit 2
fi

cat <<NETPLAN
# Pneuma: ${iface} is IPv4-only ON PURPOSE. The host's IPv6 egress to ghcr.io is
# dead (connection reset), and an IPv6 address here makes containerd prefer a
# path that cannot complete a pull. Generated by derive-ipv4-netplan.sh from the
# live interface — re-run setup.sh after any re-addressing.
network:
  version: 2
  ethernets:
    ${iface}:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      link-local: [ipv4]
      addresses: ["${cidr}"]
      nameservers:
        addresses: [${dns}]
      routes:
        - to: default
          via: ${gw}
NETPLAN
